export default {
  ru: {
    index: 'ru',
    langNumber: '1',
    startGame: 'Начать раш',
    ready: 'Готов?',
    go: 'Погнали!',
    sec: 'сек',
    target: 'цель',
    targetReached: 'цель достигнута',
    clickToFinish: 'нажмите, чтобы завершить',
    stageClear: 'Этап завершен!',
    result: 'результат',
    newRecord: 'новый рекорд!',
    forRewardleft: 'этапов до награды осталось:'
    // rating: 'Рейтинг',
    // forAllTime: 'За все время',
    // forMonth: 'За месяц',
    // back: 'Назад',
    // members: 'Участников:',
    // record: 'Мой рекорд:',
    // bloodType: 'Группа крови',
    // stage: 'Раунд:',
    // time: 'Время:',
    // score: 'Очки:',
    // wellcome: 'Добро пожаловать!',
    // howToPlay: 'Как играть?',
    // discription: 'Меняйте местами фигуры на поле.\nФормируйте цепочки в три или более\nодинаковых фигур в ряд.\n\nПолучайте очки за найденные\nцепочки.',
    // next: 'Далее',
    // continue: 'Продолжить',
    // stageComplete: 'Раунд завершён!',
    // gameOver: 'Игра завершена',
    // youEarned: 'Вы набрали',
    // points: 'очков!',
  },
}